### PR TITLE
Refactoring, markdown README and Treasure

### PR DESCRIPTION
**Pull request by xsebek**
This is quite a change, but I liked this repo more than others. Hope it serves somebody else too! 😄 

Someone more diligent should make a section mentioning others and add LICENSE 🤔

### CODE REVIEW

**Comment by xsebek** [comment]
Also I never used curses before, so if there is some documentation readable by humans, I would very much like to fix the bugs that are left and those I created 😄

**Comment by alts** [comment]
Wow! @xsebek thank you so much! This is really impressive. I wanted to respond as soon as I could to thank you, and also to let you know that over the next couple of days I'm going to be rather busy. But hopefully I can get around to exploring all of your changes around Wednesday or Thursday. 

Thank you again for the PR! And I'm so glad you've found this tool helpful enough to make such a big contribution.

You mentioned some bugs with `curses`. I might be able to help out. What kinds of problems were you encountering?

**Comment by xsebek** [comment]
Thanks, sure take your time 🙂 I might not even use this myself, but perhaps someone at my faculty could find it useful.

---

There are scenarios in which a thrown exception does not behave well, in particular because `Board.__del__` will then be called and can throw its own exception. There is something that interacts with how the exception is printed, with newline moved as if not using `\r`. I also encountered the exception being shown and then screen `clear`ed.

```shell
$ ./karel_run.py levels/04_140x50.karelmap
Failed parsing map:
                   Window too small (197, 12) and World too big (139, 49)
```
Viewed in VIM, the output looks like this:
```
Failed parsing map:
Window too small (197, 12) and World too big (139, 49)
^[[?1049h^[[1;12r^[(B^[[m^[[4l^[[?7h^[[12;1H^[[?1049l^M^[[?1l^[>
```

Some of this could be solved by taking responsibility from Board and using `__init__` parameters. 🤔 Perhaps I could even split the class in two (board+window) and create some simple bash tests.

**Review by alts — COMMENTED** [review]
> There are scenarios in which a thrown exception does not behave well

Ah, yeah when the screen is initialized, the terminal mode changes such that "\n" does not carry with it an implicit carriage return. You can add an explicit carriage return to the print statement if you like. Another approach would be to explicitly call `curses.endwin()` before trying to print directly to the screen

**Comment by xsebek** [comment]
OK, I think all the obvious errors are fixed and I did some more cleaning 😄

**Comment by alts** [comment]
Thank you again, Ondřej! I've hard some time to read through all of the changes, and try a few example programs as well. I'm going to go ahead and merge this, since there are a number of great changes in here (especially that README, wow). I wanted to share a few thoughts that I had for changes that I'd likely make after merging, to get your thoughts. I'm not going to ask you to make the changes in your branch too (unless you think you'd benefit from having the changes in your repo as well).

You added a `turn_right` function to the available functions in `karel_run.py`. That omission was intentional. When I've taught with this, the absence of a `turn_right` is always a (good) frustration that the learner has, and is usually the first instance of defining their own function. That's why in the pothole examples, Karel starts in the lower right. It makes turning right the natural direction, but not available. The learner can create their own "higher level" function by using multiple of the "lower level" ones. I'll probably remove `turn_right` post-merge.

The progression of levels in the repo corresponded with the curriculum that I'd been teaching (and the curriculum I'd been taught with). I'm not sure how the new levels fit into that flow. I'll likely reorder the levels once I get a sense of what specific skill the learner is supposed to learn from the window levels (thank you for the link to that paper by the way).

The progression was something like this: 
01 - calling functions
02 - defining functions (turn_right)
03 - loops
04 - fencepost problem, thinking about what the looping condition really is
etc.

I wanted to share these likely changes with you before I made them, post merge. I really appreciate all the work you did here, and I'm excited that you (or your colleagues) are getting some use out of this! Thank you again

**Comment by xsebek** [comment]
Good to hear, I am perfectly fine with the changes and I did wonder what the levels were for :)

It would be great if you added this info to README.

The window levels are just an introductory example and three counterexamples. They would probably go after “loops” and they do require turn_right. Langton is just a fun program showcasing set_speed so you can push it to the end.

Please add some closing section like “other projects” and LICENSE to README too, as you are original author and I don't feel comfortable doing it in your place ;)

**Pull request merged**
